import React, { useEffect, useState } from 'react';
import GlassCard from '../components/shared/GlassCard';
import MainChart from '../components/dashboard/MainChart';
import { fetchStockQuote, fetchStockCandles, fetchTechnicalIndicators } from '../services/api';

const money = value => Number.isFinite(value) ? `₹${value.toLocaleString('en-IN', { maximumFractionDigits: 2 })}` : 'Unavailable';
const metric = (label, value) => <div className="score-pill glass" key={label}><div className="pill-label">{label}</div><div className="pill-value" style={{ color: 'var(--accent-cyan)' }}>{value ?? 'Unavailable'}</div><div className="pill-detail">FACT / derived from OHLCV where applicable</div></div>;

export default function StockAnalysis({ symbol }) {
  const [quote, setQuote] = useState(null); const [candles, setCandles] = useState([]); const [indicators, setIndicators] = useState(null); const [error, setError] = useState('');
  useEffect(() => { setQuote(null); setCandles([]); setIndicators(null); Promise.all([fetchStockQuote(symbol), fetchStockCandles(symbol), fetchTechnicalIndicators(symbol)]).then(([q, c, i]) => { setQuote(q); setCandles(c.candles); setIndicators(i.indicators); }).catch(err => setError(err.message)); }, [symbol]);
  return <div className="tab-pane active" id="tab-stock">
    <GlassCard className="panel" style={{ marginBottom: 'var(--space-5)' }}><div className="stock-detail-header"><div className="stock-detail-left"><h2>{quote?.name || symbol}</h2><div className="stock-detail-tags"><span className="tag tag-info">{quote?.provenance?.classification || 'UNAVAILABLE'}</span><span className="tag tag-info">{quote?.provenance?.source || 'No approved provider'}</span><span className="tag tag-info">{quote?.provenance?.latency || 'NO DATA'}</span></div><div className="stock-detail-meta"><span>As of: {quote?.marketDataTimestamp || 'Unavailable'}</span><span>Source tier: {quote?.provenance?.sourceTier || '—'}</span></div></div><div className="stock-detail-right"><div className="big-price">{money(quote?.price)}</div>{quote && <div className={quote.change >= 0 ? 'text-green' : 'text-red'}>{quote.change >= 0 ? '▲' : '▼'} {Number(quote.change).toFixed(2)} ({(Number(quote.changePercent) * 100).toFixed(2)}%)</div>}</div></div>{error && <p style={{ color: 'var(--accent-yellow)' }}>{error}</p>}</GlassCard>
    <div className="grid-2" style={{ marginBottom: 'var(--space-5)' }}><GlassCard className="panel"><div className="panel-header"><div className="panel-title">Price history</div><span className="panel-meta">{candles.length ? 'Unadjusted daily OHLCV' : 'No data'}</span></div><MainChart candles={candles} label={symbol} /></GlassCard><GlassCard className="panel"><div className="panel-title">Consensus</div><p style={{ color: 'var(--text-secondary)', marginTop: 16 }}>Consensus data unavailable. A licensed consensus provider is required; ProEquity will not infer analyst ratings, targets or counts.</p></GlassCard></div>
    <GlassCard className="panel"><div className="panel-header"><div className="panel-title">Technical calculation audit</div><span className="panel-meta">Derived, reproducible</span></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 'var(--space-3)' }}>{metric('RSI (14)', indicators?.rsi?.toFixed(2))}{metric('MACD (12,26,9)', indicators?.macd?.toFixed(2))}{metric('SMA 20', money(indicators?.sma20))}{metric('ATR (14)', money(indicators?.atr14))}</div><p style={{ color: 'var(--text-secondary)', marginTop: 16 }}>Methodology: Wilder RSI(14), EMA MACD(12,26,9), SMA and ATR calculated from the chart’s provider-sourced candles. Financial statements, filings, peer comparisons and valuation remain unavailable until their primary-source connectors are configured.</p></GlassCard>
  </div>;
}
